apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dhs4ec05d-go
  janus-idp.io/tekton: dhs4ec05d-go
  backstage.io/kubernetes-id: dhs4ec05d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dhs4ec05d-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
