apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dhs4ec05d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dhs4ec05d-go 
  name: dhs4ec05d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dhs4ec05d-go 
